author_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'author_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="author_app/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('<slug>/<pk>/', views.AuthorDetailView.as_view(), name="detailed_author"),
    path('home/', views.AuthorHomePageView.as_view(), name='author_home'),
    path('update/<slug>/<pk>/', views.UserExtraUpdateView.as_view(), name='update-user-extra'), 
    path('follow-author/', views.follow_author, name="follow_author"),
]

author_app/templates/author_app/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<main class="layout__main-container">
  <main class="main">

    <header class="main__header ">
      <div class="header-feed content-container">
        <header class="header-feed__title-container">
          <div class="header-feed__title fs-heading-2 fw-bold ff-title centered-container col-center-container">
            
            
            <div class="col-center-container">
                <span>Write</span>
            </div>
            <span>Another One</span>
         
          </div>
        </header>

        <footer class="col-center-container fw-bold fs-body-3">
            <div>Sign In</div>
        </footer>
      </div>
    </header>

    <div class="main__content ">
      <div class="flex-container">

      
        <main class="content-container col-container centered-container ">
          <form method="POST" class="flex-container-1 col-container fs-body-2">
          
          
          {% csrf_token %}

          {% bootstrap_form form %}

          
          <button type="submit" class="button-pill button-green fs-body-4">
            <div class="centered-container">
              Sign In
            </div> 
          </button>
          <p>Not a member?</p>

          <a href="{% url 'author:signup' %}" class="button-pill button-blue  fs-body-4">
            <div class="centered-container">
              Register
            </div>

          </a>
          
          
          </form>
        </main>
      </div>

    </div>
</main>


{% endblock %}

author_app/templates/author_app/signup.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}



{% block content %}

<main class="layout__main-container">
  <main class="main">

    <header class="main__header ">
      <div class="header-feed content-container">
        <header class="header-feed__title-container">
          <div class="header-feed__title fs-heading-2 fw-bold ff-title centered-container col-center-container">
            
            
            <div class="col-center-container">
                <span>Write</span>
            </div>
            <span>Another One</span>
         
          </div>
        </header>

        <footer class="col-center-container fw-bold fs-body-3">
            <div>Register</div>
        </footer>
      </div>
    </header>

    <div class="main__content ">
      <div class="flex-container">

      
        <main class="content_container col-container centered-container">
          <form method="POST" class="flex-container-1 col-container container-thinnest">
          
          
          {% csrf_token %}

          <!-- {% for field in form  %}
            <div class="fs-body-2">
              <div>
                {{field.label}}
              </div>
              <div>
                {{field}}
              </div>
              <div class="text-alt-secondary">
                {{field.help_text}}
              </div>
            </div>
          {% endfor %} -->
          
          {% bootstrap_form form %}
          <br>
          <div class="flex-container text-container-thin centered-container ">
            <div class="button-container">
              <img class="icon-xxsm svg-icon-yellow" src="{% static 'svg/three-star-icon-filled.svg' %}"  alt="">
            </div>
            <p class="break-word">I haven't added a "forgot password" page yet. If you forget it
              you will have to wait until I figure out how to do it. You've been warned!</p>
          </div>

          <div class="button-container centered-container">
            <button type="submit" class="button-pill button-green">Sign Up</button>

          </div>

          </form>
        </main>
      </div>
    </div>
</main>


{% endblock %}

author_app/templates/author_app/user_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block content %}
    <main class="layout__main-container">
        <main class="main">
            
            <header class="main__header">
                <div class="header-feed content-container">
                    <header class="header-feed__title-container">
                        <div class="header-feed__title fs-heading-4 fw-bold text-main">
                            Settings
                        </div>
                        
                        
                    </header>
                    
                
                    <footer class="header-feed__footer-container">
                        
                    </footer>
                </div>
            </header>
            
            
            
            <div class="main__content col-container">
                <div class="content-container centered-container">
                    <form class="form" action="" method="POST" enctype="multipart/form-data">
                        {% bootstrap_form form %}
                        
                        {% csrf_token %}
                        
                        <div class="button-container">
                            <button type="submit" class="button-pill button-green">Update</button>

                        </div>
                        
                    </form>

                </div>
                

                    
            </div>
        </main>
    </main>
{% endblock %}