author_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'author_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="author_app/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('<slug>/<pk>/', views.AuthorDetailView.as_view(), name="detailed_author"),
    path('home/', views.AuthorHomePageView.as_view(), name='author_home'),
    path('update/<slug>/<pk>/', views.UserExtraUpdateView.as_view(), name='update-user-extra'), 
    path('follow-author/', views.follow_author, name="follow_author"),
]

story_app/urls.py
from django.urls import path
from . import views

app_name = "story_app"

urlpatterns = [
    path('recommendations/', views.RecommendationsFeedView.as_view(), name="recommendations_feed"),
    path('write', views.WriteStoryCreateView.as_view(), name='write'),
    path('story/<author_id>/<slug>/<pk>/', views.StoryDetailView.as_view(), name='detailed_story'),
    path('update-story/<author_id>/<slug>/<pk>/', views.StoryUpdateView.as_view(), name='update-story'),
    path('delete/<slug>/<pk>', views.StoryDeleteView.as_view(), name="delete-story"),
    path('lists/<owner>/', views.ListsListView.as_view(), name='author-list'),
    path('list/<owner>/<slug>/<pk>/', views.ListDetailView.as_view(), name='detailed_list'),
    path('new-list/', views.ListCreateView.as_view(), name='new-list'),
    path('update-list/<owner>/<slug>/<pk>/', views.ListUpdateView.as_view(), name='update-list'),
    path('pinned-lists/<owner>/', views.PinnedListsView.as_view(), name='pinned-lists'),
    path('delete/<owner>/<slug>/<pk>', views.ListDeleteView.as_view(), name="delete-list"),
    path('tag/<slug>/', views.TagDetailView.as_view(), name='detailed-tag'),
    path('explore/', views.SearchPageView.as_view(), name='explore'),
    path('search/stories/', views.StorySearchResultsView.as_view(), name='story-search-results'),
    path('search/authors/', views.AuthorSearchResultsView.as_view(), name='author-search-results'),
    path('search/tags', views.TagSearchResultsView.as_view(), name='tag_search_results'),
    path('like/', views.like_story, name="like_story_ajax"),
    path('pin-list/', views.pin_list, name="pin_list"),
    path('follow-tag/', views.follow_tag, name="follow_tag"),
    path('add-story-to-list/', views.add_story_to_list, name="add_story_to_list"),
]

wao_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from story_app import views as story_views
from author_app import views as author_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('story/', include('story_app.urls', namespace='story')),
    path('author/', include("author_app.urls", namespace="author")),
    path('author/', include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/story_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block content %}
    <main class="layout__main-container">
        <main class="main">
            
            <header class="main__header">
                <div class="header-feed content-container">
                    <header class="header-feed__title-container">
                        <div class="header-feed__title fs-heading-4 fw-bold text-main">
                            Delete Story
                        </div>
                        
                        
                    </header>
                    
                
                    
                </div>
            </header>
            
            
            
            <div class="main__content col-container">
                <div class="content-container centered-container">
                    {% if request.user == object.author_id %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="fs-heading-4">
                            <div>
                                Are you sure you want to delete "{{object}}"?
                            </div> 
                            <div>
                                There is not turning back from this.
                            </div> 
                        </div>
                        <div class="button-container">
                            <button type="submit" class="button-pill button-red">Delete</button>
                            
                            <a class="button-pill button-blue" href="{% url 'author:detailed_author' request.user request.user.pk %}">No, take me back!</a>
                        </div>

                    </form>
                    {% endif %}
                </div>
                

                    
            </div>
        </main>
    </main>
{% endblock %}

templates/story_lists.html
{% extends 'base.html' %}
{% load static %}

{% block content %}




    <main class="layout__main-container">
        <main class="main">

            <header class="main__header">
                <div class="header-feed content-container">
                    <header class="header-feed__title-container">
                        <div class="header-feed__title fs-heading-4 fw-bold text-main">
                            Lists
                        </div>
                        
                        <div class="button-container">
                            <a href="{% url 'story:new-list' %}">
                                <div class="button-pill button-blue">
                                    New List
                                </div>
                            </a>
                            
                        </div>
                    </header>
                    
                
                    <footer class="header-feed__footer-container">
                        <div class="header-feed__footer-tab--active">
                            <a href="{% url 'story:author-list' request.user %}">

                                Your Lists
                            </a>
                        </div>
                        <div class="header-feed__footer-tab">
                            <a href="{% url 'story:pinned-lists' current_user.pk %}">

                                Pinned
                            </a>
                        </div>
                    

                    </footer>
                </div>
            </header>
            
            <div class="main__content col-container">
                {% for list in object_list %}
                <div class="list-card__container">
                    <article class="list-card content-container">
                        <div class="list-card__main-container">
                            <div class="list-card__text-container">
                                <header class="list-card__header">
                                        <a href="{% url 'story:detailed_list' list.user list.slug list.pk %}">
                                            <div class="list-card__title fs-heading-4 fw-bold">
                                                {{list.name}}
                                            </div>
                                        </a>
                                        
                                        
                                    </header>
                                    <main class="list-card__description fs-body-3 text-secondary">
                                        {{list.description}}
                                    </main>
                                    
                                </div>
                            <footer class="list-card__footer-container text-alt-secondary">
                                <div class="list-card__footer">

                                    <div class="list-card__footer-info">
                                        
                                        <div class="list-card__author">
                                            <!-- <a class="list-card__author" href="{% url 'author:detailed_author' current_user.user.username current_user.user.id %}">
                                                <img class="icon-xsm icon-round" src="{{ current_user.cover_image.url }}" alt="">
                                                <div class="text-main">
                                                    @{{ list.user.username }}
                                                </div>

                                            </a>
                                            
                                            <div class="button-container">
                                                ·
                                            </div> -->
                                           
                                            <div class="list-card__footer-about">
                                                
                                                
                                                <div class="button-container">
                                                    {{ list.stories.all.count}} stories
                                                    
                                                </div>
                                                <!-- <div class="button-container">
                                                    ·
                                                </div>
                                                <div class="button-container">
                                                    <span id="{{list.pk}}-pin-count">{{list.pinner_count}}</span> Pins
                                                </div> -->
                                                
                                            </div>
                                        </div>
                                    </div>

                                    <div class="button-container">
                                        <!-- <div class="button-container">
                                            {% if request.user in list.pinners.all %}
                                            <div id="pin-list-button" onclick="pinList(this.value)" value="{{list.pk}}">
                                                <div class="">
                                                    {% csrf_token %}
                                                    <img class="icon-xsm" id="{{ list.pk }}-pinned" src="{% static 'svg/in-list-icon.svg' %}">
                                                    
                                                </div>
                                            </div>
                                            
                                            {% else %}
                                            <div id="pin-list-button" onclick="pinList(this.value)" value="{{list.pk}}">
                                                <div class="">
                                                    {% csrf_token %}
                                                    <img class="icon-xsm" id="{{ list.pk }}-pinned" src="{% static 'svg/add-to-list-icon.svg' %}">
                                                </div>
                                            </div>
                                            
                                            {% endif %}
                                        </div> -->
                                        
                                        <div class="button-container">
                                            <div class="dropdown">
                                                <button class="" data-toggle="dropdown">
                                                    <img class="icon-xsm" id="svg-icon-primary" src="{% static 'svg/more-icon.svg' %}" alt="">
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-right fs-body-4">
                                                
                                                <a class="dropdown-item" href="{% url 'story:update-list' list.user list.slug list.pk %}">Edit</a>
                                                

                                                <a class="dropdown-item" href="{% url 'story:delete-list' list.user list.slug list.pk %}">Delete</a>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                
                                
                            </footer>
                            </div>
                            
                        </article>
                    
                </div>
                
                {% endfor %}
            </div>
        </main>
    </main>
{% endblock %}

{% block scripts %}
<script>
    function pinList(listClicked){
        const list = listClicked
        
        $.ajax({
            type: 'POST',
            url: '{% url "story:pin_list" %}',
            data: {
                listpk: listClicked,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            cache: false,
            success: function(json) {
                document.getElementById(`${list}-pin-count`).innerHTML = json['result'];
                document.getElementById(`${list}-pinned`).src = json['pinned']
                console.log('success')
            },
            error: function(xhr, errmsg, err) {
                
            }
        });
    }
</script>
{% endblock %}

templates/story_search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="layout__main-container">
        <main class="main">

            <header class="main__header text-secondary">
                <div class="header-feed content-container">
                    <div class="search-bar-container">
                        
                        <form class="search-bar" action="{% url 'story:story-search-results' %}" method="GET">
                            <img class="icon-xsm" src="{% static 'svg/search-icon.svg' %}" alt="">
                            <input class="search-bar-input" type="text" name="q" id="" placeholder="search">
                        </form>
                        
                        
                       

                    </div>
                    <header class="header-feed__title-container">
                        <div class="header-feed__title fs-heading-3 fw-bold text-main">
                            <span class="text-secondary">{{ object_list.all.count }} Results for "<span class="text-main">{{query}}</span>"</span>
                        </div>
                        
                    </header>
                    
                    <footer class="header-feed__footer-container">
                        
                        <div class="header-feed__footer-tab--active">
                            Stories
                        </div>
                        
                        <form class="header-feed__footer-tab" action="{% url 'story:author-search-results' %}" method="GET">
                            <input type="hidden" name="q" value="{{query}}">
                            <input type="submit" value="Authors">
                        </form>
                       
                        <form class="header-feed__footer-tab" action="{% url 'story:tag_search_results' %}" method="GET">
                            <input type="hidden" name="q" value="{{query}}">
                            <input type="submit" value="Tags">
                        </form>
                    </footer>
                </div>
            </header>
            
            
            <div class="main__content col-container">
                {% for story in object_list %}
                <div class="story-card__container">
                    <article class="story-card content-container">
                        <a href="{% url 'author:detailed_author' story.author_id.username story.author_id.id %}">
                            <header class="story-card__header ff-body fs-body-3">
                                {% for user_extra in user_extras %}
                                {% if story.author_id.pk == user_extra.user.pk %}
                                <img class="icon-xsm icon-round" src="{{ user_extra.cover_image.url }}" alt="">
                            
                                {% endif %}
                                {% endfor %}
                                
                                <div>
                                    {{story.author_id}}
                                </div>
                                <div>
                                    ·
                                </div>
                                <div class="text-alt-secondary">
                                    {{story.show_time_since}}
                                </div>
                                
                                
                            </header>
                        </a>
                        <main class="story-card__main-container">
                            <div class="story-card__text-container">
                                <header class="story-card__title ff-title fs-heading-3 fw-bold">
                                        <a href="{% url 'story:detailed_story' story.author_id story.slug story.pk %}">
                                            {{story.title}}
                                        </a>
                                    </header>

                                    <main class="story-card__description ff-read fs-body-3 fw-reg">
                                        {{story.content_minified | slice:":180" }}...
                                    </main>
                                <footer class="story-card__footer-container">
                                    <footer class="story-card__footer">
                                        
                                        <div>
                                            
                                            <a href="{% url 'story:detailed-tag' story.tags.all.last.slug %}">
                                                <div class="tag-card__tag-icon">
                                                    {{ story.tags.all.last.name }}
                                                </div>
                                            </a>
                                           

                                        </div>
                                        
                                        <div class="story-card__buttons">
                                            <div class="button-container">
                
                                                {% if request.user in story.likes.all %}
                                                <button id="like-story-button" onclick="storyClick(this.value)" value="{{story.pk}}">
                                                    <div class="button-pill button-pill-md">
                                                        {% csrf_token %}
                                                        <img class="icon-xxsm svg-icon-accent" id="{{story.pk}}-like-story-icon" src="{% static 'svg/like-icon-filled.svg' %}" alt="">
                                                        <span id="{{story.pk}}-like-count">{{story.like_count}}</span>
                                                    </div>
                                                </button>
                                                {% else %}
                                                <button id="like-story-button" onclick="storyClick(this.value)" value="{{story.pk}}">
                                                    <div class="button-pill button-pill-md">
                                                        {% csrf_token %}
                                                        <img class="icon-xxsm svg-icon-accent" id="{{story.pk}}-like-story-icon" src="{% static 'svg/like-icon.svg' %}" alt="">
                                                        <span id="{{story.pk}}-like-count">{{story.like_count}}</span>
                                                    </div>
                                                </button>
                                                {% endif %}
                
                                                {% if request.user == story.author_id %}
                                                <div class="dropdown">
                                                    <button class=""  data-toggle="dropdown" >
                                                        <img class="icon-xsm svg-icon-primary" src="{% static 'svg/more-icon.svg' %}" alt="">
                                                    </button>
                                                    <div class="dropdown-menu fs-body-4">
                                                    
                                                        <a class="dropdown-item" href="{% url 'story:update-story' story.author_id story.slug story.pk %}">Edit</a>
                                                        <a class="dropdown-item" href="{% url 'story:delete-story' story.slug story.pk %}">Delete</a>
                                                
                
                                                    </div>
                                                </div>
                                                {% endif %}
                                                
                
                                                <div class="dropdown">
                                                    
                                                    <button class=""  data-toggle="dropdown">
                                                        <img id="" class="icon-xsm svg-icon-primary" src="{% static 'svg/bookmark-add.svg' %}" alt="">
                                                    </button>
                                                    <div class="dropdown-menu fs-body-4">
                                                        {% for list in current_user.lists.all %}
                                                        {% if story in list.stories.all %}
                                                        <div class="dropdown-item">
                                                            <button class="button-container" id="add-to-list-button" onclick="addStoryToList(this.value)" value="{{story.pk}}|{{list.pk}}">
                                                                {% csrf_token %}
                                                                <img class="icon-xsm" id="{{story.pk}}-in-{{list.pk}}" src="{% static 'svg/check-box-icon-filled.svg' %}" alt="">
                                                                <span>{{list}}</span>
                                                            </button>
                                                        
                                                        </div>
                                                        {% else %}
                                                        <div class="dropdown-item">
                                                            <button class="button-container" id="add-to-list-button" onclick="addStoryToList(this.value)" value="{{story.pk}}|{{list.pk}}">
                                                                {% csrf_token %}
                                                                <img class="icon-xsm" id="{{story.pk}}-in-{{list.pk}}" src="{% static 'svg/check-box-icon.svg' %}" alt="">
                                                                <span>{{list}}</span>
                                                            </button>
                                                        
                                                        </div>
                                                        {% endif %}
                                                        {% endfor %}
                                                        
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </footer>
                                </footer>
                            </div>

                            <a class="story-card__image-container" href="{% url 'story:detailed_story' story.author_id story.slug story.pk %}">
                                <img class="story-card__image" src="{{ story.cover_image.url}}" alt="">
                            </a>
                        </main>
                        
                        
                            
                    </article>
                </div> 
                
                <div class="flex-container">
                    <div class="content-container divider-item">

                    </div>
                </div>

                {% endfor %}
            
                
            </div>
        </main>
    </main>      
{% endblock %}

templates/tag_search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="layout__main-container">
        <main class="main">

            <header class="main__header text-secondary">
                <div class="header-feed content-container">
                    <div class="search-bar-container">
                        
                        <form class="search-bar" action="{% url 'story:tag_search_results' %}" method="GET">
                            <img class="icon-xsm" src="{% static 'svg/search-icon.svg' %}" alt="">
                            <input class="search-bar-input" type="text" name="q" id="" placeholder="search">
                        </form>
                        
                        
                       

                    </div>
                    <header class="header-feed__title-container">
                        <div class="header-feed__title fs-heading-3 fw-bold text-main">
                            <span class="text-secondary">{{ object_list.all.count }} Results for "<span class="text-main">{{query}}</span>"</span>
                        </div>
                        
                    </header>
                    
                    <footer class="header-feed__footer-container">
                        
                        <form class="header-feed__footer-tab" action="{% url 'story:story-search-results' %}" method="GET">
                            <input type="hidden" name="q" value="{{query}}">
                            <input type="submit" value="Stories">
                        </form>
                        
                        <form class="header-feed__footer-tab" action="{% url 'story:author-search-results' %}" method="GET">
                            <input type="hidden" name="q" value="{{query}}">
                            <input type="submit" value="Authors">
                        </form>
                       
                        <div class="header-feed__footer-tab--active">
                            Tags
                        </div>
                    </footer>
                </div>
            </header>
            
            
            <div class="main__content col-container">
            
            {% for tag in object_list %}
            <div class="tag-card__container">
                <div class="content-container tag-card">
                    <div class="tag-card__left-container">
                        <div class="button-container">
                            <img class="icon-sm" id="svg-icon-secondary" src="{% static 'svg/tag-icon.svg' %}" alt="">
                        </div>
                        <a href="{% url 'story:detailed-tag' tag.tag.slug %}">
                            <div class="tag-card__text-container">
                                <div class="ff-title fs-body-1 fw-bold">
                                    {{tag.tag.name}}
                                </div>
                                <div class="tag-card__footer fs-body-3 text-secondary">
                                    <div>
                                        <span id="{{tag.pk}}-follower-count">{{tag.follower_count}}</span> Followers
                                    </div>
                                    <div>
                                        <span>{{tag.story_count}}</span> Stories
                                    </div>
                                </div>
                                
                            </div>
                        </a>
                    </div>
                        <div class="tag-card__follow-button button-container button-pill button-green">
                            {% if tag.tag in current_user.tags.all %}
                            <button id="follow-tag-button" onclick="followTag(this.value)" value="{{tag.pk}}">
                                
                                {% csrf_token %}
                                <div id="{{tag.pk}}-followed">Following</div>
                                
                            </button>
                            {% else %}
                            <button id="follow-tag-button" onclick="followTag(this.value)" value="{{tag.pk}}">
                                
                                {% csrf_token %}
                                <div id="{{tag.pk}}-followed">Follow</div>
                                
                            </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            
            {% endfor %}
                
            </div>
        </main>
    </main>      
{% endblock %}

{% block scripts %}
<script>
    function followTag(tagClicked){
        const tag = tagClicked
        $.ajax({
            type: 'POST',
            url: '{% url "story:follow_tag" %}',
            data: {
                tagpk: tagClicked,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            cache: false,
            success: function(json) {
                document.getElementById(`${tag}-follower-count`).innerHTML = json['result'];
                document.getElementById(`${tag}-followed`).innerHTML = json['followed']
                console.log('success')
            },
            error: function(xhr, errmsg, err) {
                
            }
        });
    }
</script>
{% endblock %}